'use strict';

exports.SINGLE_STEP = 1;
exports.BREAKPOINT = 2;
exports.FRAME_POP = 3;
exports.EXCEPTION = 4;
exports.USER_DEFINED = 5;
exports.THREAD_START = 6;
exports.THREAD_DEATH = 7;
exports.THREAD_END = 7;
exports.CLASS_PREPARE = 8;
exports.CLASS_UNLOAD = 9;
exports.CLASS_LOAD = 10;
exports.FIELD_ACCESS = 20;
exports.FIELD_MODIFICATION = 21;
exports.EXCEPTION_CATCH = 30;
exports.METHOD_ENTRY = 40;
exports.METHOD_EXIT = 41;
exports.METHOD_EXIT_WITH_RETURN_VALUE = 42;
exports.MONITOR_CONTENDED_ENTER = 43;
exports.MONITOR_CONTENDED_ENTERED = 44;
exports.MONITOR_WAIT = 45;
exports.MONITOR_WAITED = 46;
exports.VM_START = 90;
exports.VM_INIT = 90;
exports.VM_DEATH = 99;
exports.VM_DISCONNECTED = 100;
